"""Domain package for core application contracts."""

from weather_agent.domain.auth import AuthorizationService, AuthorizedUserRepo, UnauthorizedError
from weather_agent.domain.cel import (
    ALL_ALLOWED_FUNCTION_NAMES,
    ALLOWED_FUNCTIONS,
    ALLOWED_METRICS,
    CELEvalError,
    CELEvaluationResult,
    CELEvaluator,
    ValidationResult,
    get_allowlist_for_prompt,
    validate_expression,
)
from weather_agent.domain.errors import (
    WeatherProviderError,
    WeatherProviderResponseError,
    WeatherProviderTimeoutError,
    WeatherProviderUnavailableError,
)
from weather_agent.domain.global_settings import GlobalSettingsService, GlobalUnits, SettingsRepo
from weather_agent.domain.providers import (
    ForecastProvider,
    ObservationProvider,
    WarningProvider,
)
from weather_agent.domain.rules import (
    CELValidationError,
    NotificationEvent,
    NotificationRule,
    NotificationRuleService,
    RuleCreate,
    RuleNotFoundError,
    RuleUpdate,
    ShortIdCollisionError,
    generate_short_id,
    strip_hash_prefix,
)
from weather_agent.domain.weather import (
    ForecastPoint,
    ForecastResolution,
    ForecastResult,
    LocationRef,
    ObservationPoint,
    ObservationResult,
    TimeRange,
    WarningCategory,
    WarningSeverity,
    WeatherVariable,
    WeatherWarning,
)

__all__ = [
    "ALL_ALLOWED_FUNCTION_NAMES",
    "ALLOWED_FUNCTIONS",
    "ALLOWED_METRICS",
    "AuthorizationService",
    "AuthorizedUserRepo",
    "CELValidationError",
    "CELEvalError",
    "CELEvaluationResult",
    "CELEvaluator",
    "ForecastPoint",
    "ForecastProvider",
    "ForecastResolution",
    "ForecastResult",
    "GlobalSettingsService",
    "GlobalUnits",
    "LocationRef",
    "NotificationEvent",
    "NotificationRule",
    "NotificationRuleService",
    "ObservationPoint",
    "ObservationProvider",
    "ObservationResult",
    "RuleCreate",
    "RuleNotFoundError",
    "RuleUpdate",
    "SettingsRepo",
    "ShortIdCollisionError",
    "TimeRange",
    "UnauthorizedError",
    "ValidationResult",
    "WarningCategory",
    "WarningSeverity",
    "WeatherProviderError",
    "WeatherProviderResponseError",
    "WeatherProviderTimeoutError",
    "WeatherProviderUnavailableError",
    "WeatherVariable",
    "WeatherWarning",
    "WarningProvider",
    "generate_short_id",
    "get_allowlist_for_prompt",
    "strip_hash_prefix",
    "validate_expression",
]